### ISSUE TITLE
linux arm64 support

### ISSUE THREAD

**Issue by catdevnull** [duckdb/duckdb-node-neo#54]

**Comment by jraymakers** [comment]
This should be possible, because DuckDB does have Linux aarch64 releases. I think the blocker was that GitHub didn't have Linux arm64 runners until relatively recently. It looks like they're available now, at least for some kinds of accounts; I'll look into whether they can be used in this repo.

**Comment by jraymakers** [comment]
I've published a new version of the packages (1.1.3-alpha.7) that include experimental Linux arm64 support.

It's experimental because I had to use cross-compilation from Linux x64. (Standard Linux arm64 GitHub runners don't appear to be available yet.) This means I couldn't run the automated tests. (Linux arm64 binaries won't run on Linux arm64.) I don't have easy access to a Linux arm64 environment, so I haven't run any manual tests on this platform, either. That said, I don't know of any reason why it wouldn't work.

If anyone tries this out, please let me know if it works for you or not.
